# Generated by Django 4.0.4 on 2022-05-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_at',
        ),
    ]
